#the number of second inbetween checking to apply effects
#larger number means less server load
#but items take longer to activate after being picked up
#and take longer to wear off after being dropd
looptime: 5


